Implement CI building
Builds currently rely on Globus' internal Jenkins coordinator and
infrastructure.  A fair number of changes here are to work with the CI
infrastructure, which is a good bit more strict about placement of files and
which utility does what task.

[sc-32896]

diff --git a/compute_endpoint/packaging/Makefile b/compute_endpoint/packaging/Makefile
--- a/compute_endpoint/packaging/Makefile
+++ b/compute_endpoint/packaging/Makefile
@@ -2,9 +2,9 @@
 
 # Work with the (apparently) different setup in OpenSUSE, where `make` doesn't
 # invoke /bin/sh in the same manner as other platforms.
-PYTHON3 := $$($(SHELL) -c "command -v /opt/globus-python/bin/python3")
+PYTHON3 := $$("$(SHELL)" -c "command -v /opt/globus-python/bin/python3")
 
-PY_FULL_VERSION := $$($(PYTHON3) -c "import sys; print('{}.{}.{}'.format(*sys.version_info))")
+PY_FULL_VERSION := $$("$(PYTHON3)" -c "import sys; print('{}.{}.{}'.format(*sys.version_info))")
 PY_MAJOR_VERSION := $(shell echo -n $(PY_FULL_VERSION) | cut -d . -f1 )
 PY_MINOR_VERSION := $(shell echo -n $(PY_FULL_VERSION) | cut -d . -f2 )
 PY_VERSION := $(PY_MAJOR_VERSION)$(PY_MINOR_VERSION)
@@ -16,18 +16,21 @@ VENV_PY := $(shell pwd)/$(VIRTUALENV)/bin/python
 # This if conditional before the PKG_ variables, so as to ensure we have setuptools;
 # not so ideal, but at the moment, I don't know how to do better.  Hmm.
 ifeq ($(wildcard $(VENV_PY)),)
-	_DUMMY := $(shell $(PYTHON3) -mvenv "$(VIRTUALENV)")
-	_DUMMY := $(shell $(VENV_PY) -mpip install -U pip -U setuptools)
+	_DUMMY := $(shell "$(PYTHON3)" -mvenv "$(VIRTUALENV)"; ln -sf "$(VIRTUALENV)" venv)
+	_DUMMY := $(shell "$(VENV_PY)" -mpip install -U pip -U setuptools)
 endif
 
 # "package name - dash" and "package name - underscore"
 PKG_NAME := "globus-compute-agent"
-PIP_NAME_D := $(shell cd ../; $(VENV_PY) setup.py --name)
+PIP_NAME_D := $(shell cd ../; "$(VENV_PY)" setup.py --name)
 PIP_NAME_U := $(shell echo $(PIP_NAME_D) | tr '-' '_')
 
-PKG_VERSION := $(shell cd ../; $(VENV_PY) setup.py --version | tr '-' '~')
-PKG_WHEEL = $(PIP_NAME_U)-$(PKG_VERSION)-py$(PY_MAJOR_VERSION)-none-any.whl
-PREREQS_TARBALL_NAME = $(PIP_NAME_U)-prereqs-py$(PY_VERSION)-$(PKG_VERSION).tar.xz
+PKG_VERSION := $(shell cd ../; "$(VENV_PY)" setup.py --version | tr '-' '~')
+PKG_WHEEL := $(PIP_NAME_U)-$(PKG_VERSION)-py$(PY_MAJOR_VERSION)-none-any.whl
+PKG_SOURCE_DIR := $(PIP_NAME_U)-$(PKG_VERSION)
+PKG_TARBALL := $(PKG_SOURCE_DIR).tar.gz
+PREREQS_DIR := $(PIP_NAME_U)-prereqs-py$(PY_VERSION)-$(PKG_VERSION)
+PREREQS_TARBALL_NAME = $(PREREQS_DIR).tar.gz
 
 OS_CODENAME := $(shell test -f /etc/os-release && . /etc/os-release; echo $${VERSION_CODENAME:-focal})
 
@@ -62,7 +65,10 @@ show_vars:   ##-For debugging, show the Makefile variables; will install a venv
 	@echo "PIP_NAME_U           : $(PIP_NAME_U)"
 	@echo "PKG_NAME             : $(PKG_NAME)"
 	@echo "PKG_VERSION          : $(PKG_VERSION)"
+	@echo "PREREQS_DIR          : $(PREREQS_DIR)"
 	@echo "PREREQS_TARBALL_NAME : $(PREREQS_TARBALL_NAME)"
+	@echo "PKG_SOURCE_DIR       : $(PKG_SOURCE_DIR)"
+	@echo "PKG_TARBALL          : $(PKG_TARBALL)"
 	@echo "PKG_WHEEL            : $(PKG_WHEEL)"
 	@echo
 	@echo "  Override python path with PYTHON3 variable:"
@@ -70,14 +76,16 @@ show_vars:   ##-For debugging, show the Makefile variables; will install a venv
 
 .PHONY: clean
 clean:  ##-Remove the venv, build/ dist/, prereqs tarball, and the package wheel
-	rm -rf -- "$(VIRTUALENV)" build/ dist/ "$(PREREQS_TARBALL_NAME)" "$(PKG_WHEEL)"
+	rm -rf -- "$(VIRTUALENV)" venv build/ dist/ "$(PREREQS_TARBALL_NAME)" "$(PKG_WHEEL)"
 
 .PHONY: distclean
 distclean: clean  ##-Run `clean` target, then additionally remove venv-*, *tar.xz, *whl
 	rm -rf -- venv-* "$(PIP_NAME_U)"-*tar.xz "$(PIP_NAME_U)"-*whl
 
 _build_needs:
-	@/bin/echo -e "\033[36;1;40mChecking build dependencies before starting build\033[m ...\n"
+	@([ -t 1 ] && _C="\033[36;1;40m" _R="\033[m"; \
+	  /bin/echo -e "$${_C}Checking build dependencies before starting build$${_R} ...\n"; \
+	)
 	@[ -x "$$(command -v git)" ] || { echo "'git' not found; missing 'git' package?"; exit 1; }
 	@[ -x "$$(command -v xz)" ] || { echo "'xz' not found; missing 'xz' package?"; exit 1; }
 	@[ -x "$$(command -v sed)" ] || { echo "'sed' not found; missing 'sed' package?"; exit 1; }
@@ -92,20 +100,21 @@ $(VENV_PY): _build_needs
 		echo "    make PYTHON3=/path/to/python"; \
 		exit 1; \
 	fi
-	$(PYTHON3) -mvenv $(VIRTUALENV)
-	. $(VIRTUALENV)/bin/activate
-	@$(VENV_PY) -m pip install -U pip -U setuptools -U build
+	"$(PYTHON3)" -mvenv "$(VIRTUALENV)"
+	ln -sf "$(VIRTUALENV)" venv
+	. venv/bin/activate
+	@"$(VENV_PY)" -m pip install -U pip -U setuptools -U build
 
 $(PKG_WHEEL): $(VENV_PY)
 	(   rm -rf build/ \
 	 && git clone ../../ build/ \
 	 && cd build/compute_endpoint/ \
-	 && echo -n "    Git Tag: " \
-	 && if ! git describe --tags --exact-match; then \
-	   { /bin/echo -e "\nBUILD COMPUTE FROM A RELEASE TAG (current branch: $$(git branch --show-current))"; exit 1; } \
+	 && if git describe --tags --exact-match 2> /dev/null; \
+	    then { echo "    Git Tag: $$(git describe --tags --exact-match)"; }; \
+	    else { echo "    Git Branch: $$(git rev-parse HEAD) ($$(git describe --tags))"; }; \
 	    fi \
 	 && rm -rf tests/ \
-	 && $(VENV_PY) -m build --wheel -o ../../ \
+	 && "$(VENV_PY)" -m build -o ../../ \
 	)
 
 wheel: $(PKG_WHEEL)  ##-Make the wheel (note that this does *not* include dependencies)
@@ -115,24 +124,32 @@ $(PREREQS_TARBALL_NAME): $(VENV_PY) $(PKG_WHEEL)
 
 prereq_tarball: $(PREREQS_TARBALL_NAME)  ##-Make a tarball of wheel dependencies
 
-dist: $(PREREQS_TARBALL_NAME)  ##-Make the dist/ directory with prereqs and wheel ready for packaging step
-	rm -rf dist/ \
-	  && mkdir dist/ \
-	  && cp $(PREREQS_TARBALL_NAME) $(PKG_WHEEL) dist/
+_dist:
+	rm -rf dist/ && mkdir dist/
+	cp "$(PKG_WHEEL)" dist/
 
-deb_build_needs:  ##-Check that necessary executables are available before starting the DEB build.
-	@[ -x "$$(command -v dpkg-checkbuilddeps)" ] || { echo "'dpkg-checkbuilddeps' not found; missing 'dpkg-dev' package?"; exit 1; }
-	@dpkg-checkbuilddeps
+	# For CI, which does things differently than this Makefile:
+	#   - append PKG_WHEEL to *prereqs* tarball
+	#   - append package_shim.sh to *package* tarball
+	(   _prereq_dir="$$(tar -tf "$(PREREQS_TARBALL_NAME)" | head -1)" \
+	 && _pkg_dir="$$(tar -tf "$(PKG_TARBALL)" | head -1)" \
+	 && cd dist/ \
+	 && tar -xf "../$(PREREQS_TARBALL_NAME)" \
+	 && cp "$(PKG_WHEEL)" "$${_prereq_dir}" \
+	 && tar -czf "$(PREREQS_TARBALL_NAME)" "$${_prereq_dir}" \
+	 && rm -r "$${_prereq_dir}" \
+	 && tar -xf "../$(PKG_TARBALL)" \
+	 && cp "../package_shim.sh" "$${_pkg_dir}" \
+	 && tar -czf "$(PKG_TARBALL)" "$${_pkg_dir}" \
+	 && rm -r "$${_pkg_dir}" \
+	)
 
-deb: deb_build_needs dist  ##-Build a Debian package of the Globus Compute Endpoint (.deb)
+dist: $(PREREQS_TARBALL_NAME) _dist    ##-Make the dist/ directory with prereqs and wheel ready for packaging step
+	rm "$(PKG_WHEEL)" "$(PKG_TARBALL)" "$(PREREQS_TARBALL_NAME)"
+
+_setup_dist_for_deb:
 	(   cd dist/ \
-	 && rm -rf debbuild/ \
-	 && mkdir -p debbuild/$(PKG_NAME)/wheels/ \
-	 && tar -C debbuild/$(PKG_NAME)/wheels/ -xf "$(PREREQS_TARBALL_NAME)" \
-	 && cp $(PKG_WHEEL) debbuild/$(PKG_NAME)/wheels/ \
-	 && cp -R ../debian debbuild/$(PKG_NAME)/ \
-	 && cp ../package_shim.sh debbuild/$(PKG_NAME)/ \
-	 && cd debbuild/$(PKG_NAME)/ \
+	 && cp -R ../debian ./ \
 	 && mv debian/changelog.in.in debian/changelog \
 	 && sed -i debian/changelog \
 	    -e "s/@PACKAGE_NAME@/$(PKG_NAME)/g" \
@@ -146,29 +163,59 @@ deb: deb_build_needs dist  ##-Build a Debian package of the Globus Compute Endpo
 	    -e "s/@PACKAGE_NAME@/$(PKG_NAME)/g" \
 	    -e "s/@PACKAGE_VERSION@/$(PKG_VERSION)/g" \
 	    -e "s/@PIP_NAME@/$(PIP_NAME_D)/g" \
+	)
+
+setup_dist_for_deb: dist _setup_dist_for_deb  ##-Place Debian-build required files in dist/
+
+deb_build_needs:  ##-Check that necessary executables are available before starting the DEB build.
+	@[ -x "$$(command -v dpkg-checkbuilddeps)" ] || { echo "'dpkg-checkbuilddeps' not found; missing 'dpkg-dev' package?"; exit 1; }
+	@dpkg-checkbuilddeps
+
+_deb:
+	(   cd dist/ \
+	 && rm -rf debbuild/ \
+	 && mkdir -p debbuild/$(PKG_NAME)/prereqs/ \
+	 && cp -R debian debbuild/$(PKG_NAME)/ \
+	 && tar -C debbuild/$(PKG_NAME)/prereqs/ --strip 1 -xf "$(PREREQS_TARBALL_NAME)" \
+	 && cp $(PKG_WHEEL) debbuild/$(PKG_NAME)/prereqs/ \
+	 && cp ../package_shim.sh debbuild/$(PKG_NAME)/ \
+	 && cd debbuild/$(PKG_NAME)/ \
 	 && dpkg-buildpackage -uc -us \
 	)
 	@echo "\nDEB package successfully built:"
 	@ls -lh dist/debbuild/*deb
 
-rpm_build_needs:  ##-Check that necessary executables are available before starting the RPM build.
-	@[ -x "$$(command -v rpmbuild)" ] || { echo "'rpmbuild' not found; missing 'rpmdevtools' or 'rpm-build' package(s)?"; exit 1; }
+# Reminder: deb rule is not invoked by CI; this is for one-off needs
+deb: deb_build_needs setup_dist_for_deb _deb  ##-Build a Debian package of the Globus Compute Endpoint (.deb)
 
-rpm: rpm_build_needs dist  ##-Build an RPM package of the Globus Compute Endpoint (.rpm)
+_setup_dist_for_rpm:
 	(   cd dist/ \
-	 && pwd && ls \
-	 && rm -rf rpmbuild/ \
-	 && mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SPECS,SRPMS} rpmbuild/SOURCES/$(PKG_NAME)/wheels \
-	 && tar -C rpmbuild/SOURCES/$(PKG_NAME)/wheels -xf "$(PREREQS_TARBALL_NAME)" \
-	 && cp $(PKG_WHEEL) rpmbuild/SOURCES/$(PKG_NAME)/wheels/ \
-	 && cp ../package_shim.sh rpmbuild/SOURCES/$(PKG_NAME)/ \
 	 && sed \
 	    -e "s/@PACKAGE_VERSION@/$(PKG_VERSION)/g" \
 	    -e "s/@PACKAGE_NAME@/$(PKG_NAME)/g" \
 	    -e "s/@PACKAGE_WHEEL@/$(PKG_WHEEL)/g" \
+	    -e "s/@PACKAGE_TARBALL_NAME@/$(PKG_TARBALL)/g" \
+	    -e "s/@PREREQS_TARBALL_NAME@/$(PREREQS_TARBALL_NAME)/g" \
 	    -e "s/@PIP_NAME@/$(PIP_NAME_D)/g" \
+	    -e "s/@PACKAGE_SOURCE_DIR@/$(PKG_SOURCE_DIR)/" \
+	    -e "s/@PREREQS_DIR@/$(PREREQS_DIR)/" \
 	    < ../fedora/$(PKG_NAME).spec.in > ./$(PKG_NAME).spec \
+	)
+
+setup_dist_for_rpm: dist _setup_dist_for_rpm  ##-Place RPM-build required files in dist/ (separated for CI building purposes)
+
+rpm_build_needs:  ##-Check that necessary executables are available before starting the RPM build.
+	@[ -x "$$(command -v rpmbuild)" ] || { echo "'rpmbuild' not found; missing 'rpmdevtools' or 'rpm-build' package(s)?"; exit 1; }
+
+# Reminder: rpm rule is not invoked by CI; this is for one-off needs
+_rpm:
+	(   cd dist/ \
+	 && rm -rf rpmbuild/ \
+	 && mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}/ \
+	 && cp *.tar.gz rpmbuild/SOURCES/ \
 	 && HOME="$$(pwd)" rpmbuild --define "_topdir $$(pwd)/rpmbuild" -ba ./$(PKG_NAME).spec \
 	)
 	@echo -e "\nRPM package successfully built:"
 	@ls -lh dist/rpmbuild/RPMS/**/*rpm
+
+rpm: rpm_build_needs setup_dist_for_rpm _rpm  ##-Build an RPM package of the Globus Compute Endpoint (.rpm)
